"""fourth commit

Revision ID: 986309b72806
Revises: 459ab01fece1
Create Date: 2019-09-23 11:50:34.652123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986309b72806'
down_revision = '459ab01fece1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('blog', sa.String(length=255), nullable=False))
    op.drop_column('blog', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('content', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('blog', 'blog')
    # ### end Alembic commands ###
